// src/components/About.tsx
import { Button } from "@/components/ui/button";
import dynamicIconImports from 'lucide-react/dynamicIconImports';
import { lazy, Suspense } from 'react';
import { LucideProps } from 'lucide-react';
import { useAboutContent } from "@/hooks/useMarkdownContent";
import { Mail } from "lucide-react";
import { toDynamicIconKey } from "@/lib/iconResolver";
interface IconProps extends Omit<LucideProps, 'ref'> {
  name: keyof typeof dynamicIconImports;
}

const Icon = ({ name, ...props }: IconProps) => {
  const importer = dynamicIconImports[name];
  if (!importer || typeof importer !== 'function') {
    console.warn(`Icon "${name}" not found in lucide-react dynamicIconImports`);
    return <div className="w-7 h-7" aria-hidden />;
  }
  
  const LucideIcon = lazy(() => 
    importer().catch((error) => {
      console.error(`Failed to load icon "${name}":`, error);
      return { default: (() => <div className="w-7 h-7" aria-hidden />) as any };
    })
  );
  
  return (
    <Suspense fallback={<div className="w-7 h-7" />}>
      <LucideIcon {...props} />
    </Suspense>
  );
};

export const About = () => {
  const { sections, loading } = useAboutContent();

  if (loading) {
    return (
      <section className="py-24 bg-secondary/20">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">Loading...</div>
        </div>
      </section>
    );
  }

  const mainSection = sections.find(s => s.id === 'about');
  const bioSection = sections.find(s => s.content.startsWith('# Bio'));
  const statSections = sections.filter(s => typeof s.metadata.order === 'number');
  const backgroundSection = sections.find(s => 
    s.content.startsWith('# Background') ||
    s.content.startsWith('# Notable Background') ||
    s.content.startsWith('# Parcours notable')
  );

  const bioParagraphs = bioSection?.content
    .replace('# Bio\n\n', '')
    .split('\n\n')
    .filter(p => p.trim());

  return (
    <section className="py-24 bg-secondary/20">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl sm:text-5xl font-bold mb-4">{mainSection?.metadata.title}</h2>
            <p className="text-xl text-muted-foreground">
              {mainSection?.metadata.name}
            </p>
          </div>

          <div className="bg-card border border-border rounded-lg p-8 shadow-medium mb-8">
            <div className="prose prose-lg max-w-none text-foreground">
              {bioParagraphs?.map((paragraph, idx) => (
                <p key={idx} className="text-lg leading-relaxed mb-6 last:mb-0">
                  {paragraph}
                </p>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            {statSections.sort((a, b) => (a.metadata.order ?? 0) - (b.metadata.order ?? 0)).map((stat) => {
              const iconName = (stat.metadata.icon
                ? String(stat.metadata.icon)
                : 'circle');
              const resolvedIconName = toDynamicIconKey(iconName) as keyof typeof dynamicIconImports;
              
              return (
                <div key={stat.id} className="text-center p-6 bg-card border border-border rounded-lg">
                  <div className="w-14 h-14 rounded-full bg-gradient-accent flex items-center justify-center mx-auto mb-4">
                    <Icon name={resolvedIconName} className="w-7 h-7 text-accent-foreground" />
                  </div>
                  <h3 className="text-3xl font-bold text-primary mb-2">{stat.metadata.value}</h3>
                  <p className="text-muted-foreground">{stat.metadata.label}</p>
                </div>
              );
            })}
          </div>

          <div className="text-center">
            <p className="text-lg text-muted-foreground mb-6">
              {backgroundSection?.content.replace(/^# [^\n]+\n\n?/, '')}
            </p>
            <Button variant="hero" size="lg" onClick={() => {
              const contactSection = document.getElementById("contact");
              contactSection?.scrollIntoView({ behavior: "smooth" });
            }}>
              <Mail className="mr-2" />
              Contactez-moi
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};

// src/components/About.svelte
<script lang="ts">
  import { Button, Card, LoadingState } from '@sent-tech/components-svelte';
  import Icon from '@/components/Icon.svelte';
  import { language, t } from '@/i18n/config';
  import { loadAboutContent, type Locale } from '@/lib/content';
  import type { ParsedMarkdownSection } from '@/lib/markdownLoader';

  let sections: ParsedMarkdownSection[] = [];
  let loading = true;
  let loadedLanguage: Locale | null = null;

  $: currentLanguage = ($language === 'en' ? 'en' : 'fr') as Locale;
  $: $language;
  $: if (currentLanguage !== loadedLanguage) {
    loadedLanguage = currentLanguage;
    void load(currentLanguage);
  }

  async function load(locale: Locale) {
    loading = true;
    try {
      sections = await loadAboutContent(locale);
    } catch (error) {
      console.error('Error loading about content:', error);
      sections = [];
    } finally {
      loading = false;
    }
  }

  $: mainSection = sections.find((section) => section.id === 'about');
  $: bioSection = sections.find((section) => section.content.startsWith('# Bio'));
  $: statSections = sections.filter((section) => typeof section.metadata.order === 'number');
  $: backgroundSection = sections.find(
    (section) =>
      section.content.startsWith('# Background') ||
      section.content.startsWith('# Notable Background') ||
      section.content.startsWith('# Parcours notable'),
  );
  $: bioParagraphs = (bioSection?.content || '')
    .replace('# Bio\n\n', '')
    .split('\n\n')
    .filter((paragraph) => paragraph.trim());

  function scrollToContact() {
    const contactSection = document.getElementById('contact');
    contactSection?.scrollIntoView({ behavior: 'smooth' });
  }
</script>

{#if loading}
  <section class="py-24 bg-secondary/20">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-center py-12">
        <LoadingState label={t('common.loading', 'Chargement...')} />
      </div>
    </div>
  </section>
{:else}
  <section class="py-24 bg-secondary/20">
    <div class="container mx-auto px-4 sm:px-6 lg:px-8">
      <div class="max-w-4xl mx-auto">
        <div class="text-center mb-12">
          <h2 class="text-4xl sm:text-5xl font-bold mb-4">{mainSection?.metadata.title}</h2>
          <p class="text-xl text-muted-foreground">{mainSection?.metadata.name}</p>
        </div>

        <Card class="!p-8 mb-8">
          <div class="prose prose-lg max-w-none text-foreground">
            {#each bioParagraphs as paragraph}
              <p class="text-lg leading-relaxed mb-6 last:mb-0">{paragraph}</p>
            {/each}
          </div>
        </Card>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          {#each [...statSections].sort((a, b) => (a.metadata.order ?? 0) - (b.metadata.order ?? 0)) as stat}
            <Card class="!p-6 text-center">
              <div class="w-14 h-14 rounded-full bg-gradient-accent flex items-center justify-center mx-auto mb-4">
                <Icon name={String(stat.metadata.icon || 'circle')} className="w-7 h-7 text-accent-foreground" />
              </div>
              <h3 class="text-3xl font-bold text-primary mb-2">{stat.metadata.value}</h3>
              <p class="text-muted-foreground">{stat.metadata.label}</p>
            </Card>
          {/each}
        </div>

        <div class="text-center">
          <p class="text-lg text-muted-foreground mb-6">
            {backgroundSection?.content.replace(/^# [^\n]+\n\n?/, '')}
          </p>
          <Button
            type="button"
            size="lg"
            class="inline-flex items-center justify-center gap-2 shadow-lg hover:shadow-xl transition-all"
            onclick={scrollToContact}
          >
            <Icon name="mail" className="mr-2" />
            {t('about.contactCta', 'Contactez-moi')}
          </Button>
        </div>
      </div>
    </div>
  </section>
{/if}
