// src/components/Blog.svelte
<script lang="ts">
  import Icon from '@/components/Icon.svelte';
  import Link from '@/components/Link.svelte';
  import { language, t } from '@/i18n/config';
  import { loadBlogContent, type BlogPostItem, type Locale } from '@/lib/content';

  let posts: BlogPostItem[] = [];
  let loading = true;
  let loadedLanguage: Locale | null = null;

  $: currentLanguage = ($language === 'en' ? 'en' : 'fr') as Locale;
  $: $language;
  $: if (currentLanguage !== loadedLanguage) {
    loadedLanguage = currentLanguage;
    void load(currentLanguage);
  }

  async function load(locale: Locale) {
    loading = true;
    try {
      posts = await loadBlogContent(locale);
    } catch (error) {
      console.error('Error loading blog content:', error);
      posts = [];
    } finally {
      loading = false;
    }
  }

  function parseDate(rawDate: string) {
    const isoDateMatch = rawDate.match(/^(\d{4})-(\d{2})-(\d{2})$/);
    if (isoDateMatch) {
      const [, year, month, day] = isoDateMatch;
      return new Date(Number(year), Number(month) - 1, Number(day));
    }
    return new Date(rawDate);
  }

  function formatDate(rawDate: string, locale: string) {
    const parsedDate = parseDate(rawDate);
    if (Number.isNaN(parsedDate.getTime())) return rawDate;

    const formatLocale = locale === 'fr' ? 'fr-FR' : 'en-US';
    return new Intl.DateTimeFormat(formatLocale, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }).format(parsedDate);
  }

  function isDraftPost(post: { draft?: boolean; tags?: string[] }) {
    if (post.draft) return true;
    return Array.isArray(post.tags) && post.tags.some((tag) => tag.toLowerCase() === 'draft');
  }
</script>

<section class="py-24 bg-secondary/30">
  <div class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16">
      <h2 class="text-4xl sm:text-5xl font-bold mb-4">{t('blog.title')}</h2>
      <p class="text-xl text-muted-foreground max-w-3xl mx-auto">{t('blog.subtitle')}</p>
    </div>

    {#if loading}
      <div class="text-center py-12">
        <p class="text-muted-foreground">{t('common.loading', 'Chargement...')}</p>
      </div>
    {:else if posts.length === 0}
      <div class="max-w-2xl mx-auto text-center p-8 rounded-xl border border-dashed border-border bg-card">
        <p class="text-muted-foreground">{t('blog.empty')}</p>
      </div>
    {:else}
      <div class="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-6xl mx-auto">
        {#each posts as post}
          {@const postUrl = post.url && post.url !== '#' ? post.url : `/blog/${post.id}`}
          {@const isExternal = postUrl.startsWith('http')}
          {@const publicationDate = post.date ? formatDate(post.date, currentLanguage) : t('blog.soon')}
          {@const isDraft = isDraftPost(post)}

          <div class="rounded-lg border bg-card text-card-foreground shadow-sm hover:shadow-large transition-all duration-300 hover:-translate-y-1 border-border">
            <div class="flex flex-col space-y-1.5 p-6">
              <div class="w-12 h-12 rounded-lg bg-gradient-accent flex items-center justify-center mb-4">
                <Icon name={post.icon || 'newspaper'} className="w-6 h-6 text-accent-foreground" />
              </div>
              <div class="flex items-center flex-wrap gap-4 text-sm text-muted-foreground mb-2">
                <span class="inline-flex items-center gap-1.5">
                  <Icon name="calendar" className="w-4 h-4" />
                  {publicationDate}
                </span>
                {#if post.readTime}
                  <span class="inline-flex items-center gap-1.5">
                    <Icon name="clock" className="w-4 h-4" />
                    {post.readTime}
                  </span>
                {/if}
                {#if isDraft}
                  <div class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80">
                    {t('blog.draft', 'Draft')}
                  </div>
                {/if}
              </div>
              <h3 class="text-2xl font-semibold tracking-tight">{post.title}</h3>
              <p class="text-base leading-relaxed text-sm text-muted-foreground">{post.description}</p>
            </div>

            <div class="p-6 pt-0">
              {#if isExternal}
                <a
                  href={postUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  class="inline-flex items-center gap-1.5 text-accent hover:text-accent/80 transition-colors font-medium"
                >
                  {t('blog.readArticle')}
                  <Icon name="arrow-up-right" className="w-4 h-4" />
                </a>
              {:else}
                <Link
                  href={postUrl}
                  className="inline-flex items-center gap-1.5 text-accent hover:text-accent/80 transition-colors font-medium"
                >
                  {t('blog.readArticle')}
                  <Icon name="arrow-up-right" className="w-4 h-4" />
                </Link>
              {/if}
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</section>

// src/components/Blog.tsx
import { useTranslation } from "react-i18next";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import dynamicIconImports from "lucide-react/dynamicIconImports";
import { ArrowUpRight, Calendar, Clock, LucideProps } from "lucide-react";
import { lazy, Suspense } from "react";
import { useBlogContent } from "@/hooks/useContent";
import { toDynamicIconKey } from "@/lib/iconResolver";
import { Link } from "react-router-dom";

interface IconProps extends Omit<LucideProps, "ref"> {
  name: keyof typeof dynamicIconImports;
}

const Icon = ({ name, ...props }: IconProps) => {
  const importer = dynamicIconImports[name];
  if (!importer || typeof importer !== "function") {
    console.warn(`Icon "${name}" not found in lucide-react dynamicIconImports`);
    return <div className="w-6 h-6" aria-hidden />;
  }

  const LucideIcon = lazy(() => importer());

  return (
    <Suspense fallback={<div className="w-6 h-6" />}>
      <LucideIcon {...props} />
    </Suspense>
  );
};

const parseDate = (rawDate: string) => {
  const isoDateMatch = rawDate.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (isoDateMatch) {
    const [, year, month, day] = isoDateMatch;
    return new Date(Number(year), Number(month) - 1, Number(day));
  }

  return new Date(rawDate);
};

const formatDate = (rawDate: string, locale: string) => {
  const parsedDate = parseDate(rawDate);
  if (Number.isNaN(parsedDate.getTime())) return rawDate;

  const formatLocale = locale === "fr" ? "fr-FR" : "en-US";
  return new Intl.DateTimeFormat(formatLocale, {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(parsedDate);
};

const isDraftPost = (post: { draft?: boolean; tags?: string[] }) => {
  if (post.draft) return true;
  return Array.isArray(post.tags) && post.tags.some((tag) => tag.toLowerCase() === "draft");
};

export const Blog = () => {
  const { t, i18n } = useTranslation();
  const { posts, loading } = useBlogContent();

  return (
    <section className="py-24 bg-secondary/30">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl sm:text-5xl font-bold mb-4">{t("blog.title")}</h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            {t("blog.subtitle")}
          </p>
        </div>

        {loading ? (
          <div className="text-center py-12">
            <p className="text-muted-foreground">{t("common.loading", "Chargement...")}</p>
          </div>
        ) : posts.length === 0 ? (
          <div className="max-w-2xl mx-auto text-center p-8 rounded-xl border border-dashed border-border bg-card">
            <p className="text-muted-foreground">{t("blog.empty")}</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-6xl mx-auto">
            {posts.map((post) => {
              const iconName = toDynamicIconKey(post.icon || "newspaper");
              const postUrl = post.url && post.url !== "#" ? post.url : `/blog/${post.id}`;
              const isExternal = Boolean(postUrl.startsWith("http"));
              const publicationDate = post.date ? formatDate(post.date, i18n.language) : t("blog.soon");
              const isDraft = isDraftPost(post);

              return (
                <Card key={post.id} className="hover:shadow-large transition-all duration-300 hover:-translate-y-1 border-border">
                  <CardHeader>
                    <div className="w-12 h-12 rounded-lg bg-gradient-accent flex items-center justify-center mb-4">
                      <Icon name={iconName} className="w-6 h-6 text-accent-foreground" />
                    </div>
                    <div className="flex items-center flex-wrap gap-4 text-sm text-muted-foreground mb-2">
                      <span className="inline-flex items-center gap-1.5">
                        <Calendar className="w-4 h-4" />
                        {publicationDate}
                      </span>
                      {post.readTime && (
                        <span className="inline-flex items-center gap-1.5">
                          <Clock className="w-4 h-4" />
                          {post.readTime}
                        </span>
                      )}
                      {isDraft && <Badge variant="secondary">{t("blog.draft", "Draft")}</Badge>}
                    </div>
                    <CardTitle className="text-2xl">{post.title}</CardTitle>
                    <CardDescription className="text-base leading-relaxed">{post.description}</CardDescription>
                  </CardHeader>

                  <CardContent className="pt-0">
                    {isExternal ? (
                      <a
                        href={postUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1.5 text-accent hover:text-accent/80 transition-colors font-medium"
                      >
                        {t("blog.readArticle")}
                        <ArrowUpRight className="w-4 h-4" />
                      </a>
                    ) : (
                      <Link
                        to={postUrl}
                        className="inline-flex items-center gap-1.5 text-accent hover:text-accent/80 transition-colors font-medium"
                      >
                        {t("blog.readArticle")}
                        <ArrowUpRight className="w-4 h-4" />
                      </Link>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </section>
  );
};
