// src/components/LanguageSwitcher.tsx
import { useTranslation } from 'react-i18next';
import { Globe } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface LanguageSwitcherProps {
  isScrolled?: boolean;
}

export const LanguageSwitcher = ({ isScrolled = false }: LanguageSwitcherProps) => {
  const { i18n } = useTranslation();

  const toggleLanguage = () => {
    const newLang = i18n.language === 'fr' ? 'en' : 'fr';
    i18n.changeLanguage(newLang);
    localStorage.setItem('language', newLang);
    document.documentElement.lang = newLang;
  };

  return (
    <Button
      variant="ghost"
      size="sm"
      onClick={toggleLanguage}
      className={`gap-2 text-sm font-medium transition-colors hover:text-accent hover:bg-transparent ${
        isScrolled ? "text-foreground" : "text-primary-foreground"
      }`}
    >
      <Globe className="h-4 w-4" />
      <span className="font-medium">{i18n.language === 'fr' ? 'EN' : 'FR'}</span>
    </Button>
  );
};

// src/components/LanguageSwitcher.svelte
<script lang="ts">
  import { Globe } from 'lucide-svelte';
  import { language, toggleLanguage } from '@/i18n/config';

  export let isScrolled = false;

  $: currentLanguage = $language;
</script>

<button
  type="button"
  on:click={toggleLanguage}
  class={`inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 h-9 px-3 hover:text-accent hover:bg-transparent ${
    isScrolled ? 'text-foreground' : 'text-primary-foreground'
  }`}
>
  <Globe class="h-4 w-4" />
  <span class="font-medium">{currentLanguage === 'fr' ? 'EN' : 'FR'}</span>
</button>
