// src/components/Navigation.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Menu, X } from 'lucide-svelte';
  import { t, language } from '@/i18n/config';
  import { location, navigate } from '@/lib/router';
  import LanguageSwitcher from './LanguageSwitcher.svelte';

  let isScrolled = false;
  let isMobileMenuOpen = false;
  let currentPathname = '/';

  $: currentPathname = $location.pathname;
  $: $language;
  $: navLinks = [
    { label: t('nav.services'), id: 'services' },
    { label: t('nav.sectors'), id: 'sectors' },
    { label: t('nav.values'), id: 'values' },
    { label: t('nav.blog'), id: 'blog' },
    { label: t('nav.about'), id: 'about' },
    { label: t('nav.contact'), id: 'contact' },
  ];

  onMount(() => {
    const handleScroll = () => {
      isScrolled = window.scrollY > 50;
    };

    window.addEventListener('scroll', handleScroll);
    handleScroll();

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  });

  function scrollToSection(id: string) {
    if (currentPathname === '/') {
      const element = document.getElementById(id);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
        isMobileMenuOpen = false;
        return;
      }
    }

    navigate(`/#${id}`);
    isMobileMenuOpen = false;
  }

  function handleLogoClick() {
    if (currentPathname === '/') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
      return;
    }

    navigate('/');
  }
</script>

<nav
  class={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
    isScrolled ? 'bg-background/95 backdrop-blur-md shadow-medium' : 'bg-transparent'
  }`}
>
  <div class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-20">
      <button type="button" on:click={handleLogoClick} class="flex items-center h-12">
        <img
          src="/SENT-logo.svg"
          alt="SENT-tech"
          class="h-8 md:h-10 w-auto transition-all duration-300"
          style={`filter: ${isScrolled ? 'none' : 'brightness(0) invert(1)'}`}
        />
      </button>

      <div class="hidden md:flex items-center gap-8">
        {#each navLinks as link}
          <button
            type="button"
            on:click={() => scrollToSection(link.id)}
            class={`text-sm font-medium transition-colors hover:text-accent ${
              isScrolled ? 'text-foreground' : 'text-primary-foreground'
            }`}
          >
            {link.label}
          </button>
        {/each}
        <LanguageSwitcher {isScrolled} />
      </div>

      <button type="button" class="md:hidden" on:click={() => (isMobileMenuOpen = !isMobileMenuOpen)}>
        {#if isMobileMenuOpen}
          <X class={`w-6 h-6 ${isScrolled ? 'text-foreground' : 'text-primary-foreground'}`} />
        {:else}
          <Menu class={`w-6 h-6 ${isScrolled ? 'text-foreground' : 'text-primary-foreground'}`} />
        {/if}
      </button>
    </div>

    {#if isMobileMenuOpen}
      <div class="md:hidden pb-6 bg-background/95 backdrop-blur-md">
        {#each navLinks as link}
          <button
            type="button"
            on:click={() => scrollToSection(link.id)}
            class="block w-full text-left py-3 px-4 text-foreground hover:bg-accent/10 transition-colors"
          >
            {link.label}
          </button>
        {/each}
        <div class="px-4 pt-3">
          <LanguageSwitcher isScrolled={true} />
        </div>
      </div>
    {/if}
  </div>
</nav>

// src/components/Navigation.tsx
import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Menu, X } from "lucide-react";
import { LanguageSwitcher } from "./LanguageSwitcher";
import { useLocation, useNavigate } from "react-router-dom";

export const Navigation = () => {
  const { t } = useTranslation();
  const location = useLocation();
  const navigate = useNavigate();
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    if (location.pathname === "/") {
      const element = document.getElementById(id);
      if (element) {
        element.scrollIntoView({ behavior: "smooth" });
        setIsMobileMenuOpen(false);
        return;
      }
    }

    navigate(`/#${id}`);
    setIsMobileMenuOpen(false);
  };

  const navLinks = [
    { label: t("nav.services"), id: "services" },
    { label: t("nav.sectors"), id: "sectors" },
    { label: t("nav.values"), id: "values" },
    { label: t("nav.blog"), id: "blog" },
    { label: t("nav.about"), id: "about" },
    { label: t("nav.contact"), id: "contact" },
  ];

  return (
    <nav 
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled 
          ? "bg-background/95 backdrop-blur-md shadow-medium" 
          : "bg-transparent"
      }`}
    >
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-20">
          {/* Logo */}
          <button
            onClick={() => {
              if (location.pathname === "/") {
                window.scrollTo({ top: 0, behavior: "smooth" });
                return;
              }
              navigate("/");
            }}
            className="flex items-center h-12"
          >
            <img 
              src="/SENT-logo.svg" 
              alt="SENT-tech" 
              className="h-8 md:h-10 w-auto transition-all duration-300"
              style={{
                filter: isScrolled 
                  ? "none" 
                  : "brightness(0) invert(1)"
              }}
            />
          </button>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-8">
            {navLinks.map((link) => (
              <button
                key={link.id}
                onClick={() => scrollToSection(link.id)}
                className={`text-sm font-medium transition-colors hover:text-accent ${
                  isScrolled ? "text-foreground" : "text-primary-foreground"
                }`}
              >
                {link.label}
              </button>
            ))}
            <LanguageSwitcher isScrolled={isScrolled} />
          </div>

          {/* Mobile Menu Button */}
          <button
            className="md:hidden"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
          >
            {isMobileMenuOpen ? (
              <X className={`w-6 h-6 ${isScrolled ? "text-foreground" : "text-primary-foreground"}`} />
            ) : (
              <Menu className={`w-6 h-6 ${isScrolled ? "text-foreground" : "text-primary-foreground"}`} />
            )}
          </button>
        </div>

        {/* Mobile Menu */}
        {isMobileMenuOpen && (
          <div className="md:hidden pb-6 bg-background/95 backdrop-blur-md">
            {navLinks.map((link) => (
              <button
                key={link.id}
                onClick={() => scrollToSection(link.id)}
                className="block w-full text-left py-3 px-4 text-foreground hover:bg-accent/10 transition-colors"
              >
                {link.label}
              </button>
            ))}
            <div className="px-4 pt-3">
              <LanguageSwitcher isScrolled={true} />
            </div>
          </div>
        )}
      </div>
    </nav>
  );
};
