// src/components/Services.svelte
<script lang="ts">
  import Icon from '@/components/Icon.svelte';
  import { language, t } from '@/i18n/config';
  import { loadServiceContent, type Locale, type ServiceItem } from '@/lib/content';

  export let onStrategyClick: (() => void) | undefined = undefined;
  export let onGovernanceClick: (() => void) | undefined = undefined;
  export let onDevelopmentClick: (() => void) | undefined = undefined;
  export let onOptimizationClick: (() => void) | undefined = undefined;

  let services: ServiceItem[] = [];
  let loading = true;
  let loadedLanguage: Locale | null = null;

  $: currentLanguage = ($language === 'en' ? 'en' : 'fr') as Locale;
  $: $language;
  $: if (currentLanguage !== loadedLanguage) {
    loadedLanguage = currentLanguage;
    void load(currentLanguage);
  }

  async function load(locale: Locale) {
    loading = true;
    try {
      services = await loadServiceContent(locale);
    } catch (error) {
      console.error('Error loading services content:', error);
      services = [];
    } finally {
      loading = false;
    }
  }

  function handleServiceClick(service: ServiceItem) {
    if (service.clickable && service.scrollTo) {
      if (service.id === 'strategy') {
        onStrategyClick?.();
      } else if (service.id === 'governance') {
        onGovernanceClick?.();
      } else if (service.id === 'development') {
        onDevelopmentClick?.();
      } else if (service.id === 'optimization') {
        onOptimizationClick?.();
      }

      window.setTimeout(() => {
        const section = document.getElementById(service.scrollTo as string);
        section?.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    }
  }
</script>

<section class="py-24 bg-secondary/30">
  <div class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16">
      <h2 class="text-4xl sm:text-5xl font-bold mb-4">{t('services.title')}</h2>
      <p class="text-xl text-muted-foreground max-w-3xl mx-auto">{t('services.subtitle')}</p>
    </div>

    {#if loading}
      <div class="text-center py-12">
        <p class="text-muted-foreground">{t('common.loading', 'Chargement...')}</p>
      </div>
    {:else}
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        {#each services as service}
          {#if service.clickable}
            <div
              role="button"
              tabindex="0"
              class="rounded-lg border bg-card text-card-foreground shadow-sm hover:shadow-large transition-all duration-300 hover:-translate-y-1 border-border cursor-pointer"
              on:click={() => handleServiceClick(service)}
              on:keydown={(event) => {
                if (event.key === 'Enter' || event.key === ' ') {
                  event.preventDefault();
                  handleServiceClick(service);
                }
              }}
            >
              <div class="flex flex-col space-y-1.5 p-6">
                <div class="w-12 h-12 rounded-lg bg-gradient-accent flex items-center justify-center mb-4">
                  <Icon name={service.icon} className="w-6 h-6 text-accent-foreground" />
                </div>
                <h3 class="text-2xl font-semibold tracking-tight">{service.title}</h3>
              </div>
              <div class="p-6 pt-0">
                <p class="text-base leading-relaxed text-muted-foreground">{service.description}</p>
              </div>
            </div>
          {:else}
            <div class="rounded-lg border bg-card text-card-foreground shadow-sm hover:shadow-large transition-all duration-300 hover:-translate-y-1 border-border">
              <div class="flex flex-col space-y-1.5 p-6">
                <div class="w-12 h-12 rounded-lg bg-gradient-accent flex items-center justify-center mb-4">
                  <Icon name={service.icon} className="w-6 h-6 text-accent-foreground" />
                </div>
                <h3 class="text-2xl font-semibold tracking-tight">{service.title}</h3>
              </div>
              <div class="p-6 pt-0">
                <p class="text-base leading-relaxed text-muted-foreground">{service.description}</p>
              </div>
            </div>
          {/if}
        {/each}
      </div>
    {/if}
  </div>
</section>

// src/components/Services.tsx
import { useTranslation } from "react-i18next";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import dynamicIconImports from 'lucide-react/dynamicIconImports';
import { lazy, Suspense } from 'react';
import { LucideProps } from 'lucide-react';
import { useServiceContent } from "@/hooks/useContent";

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: keyof typeof dynamicIconImports;
}

const Icon = ({ name, ...props }: IconProps) => {
  const importer = dynamicIconImports[name];
  if (!importer || typeof importer !== 'function') {
    console.warn(`Icon "${name}" not found in lucide-react dynamicIconImports`);
    return <div className="w-6 h-6" aria-hidden />;
  }
  
  const LucideIcon = lazy(() => 
    importer().catch((error) => {
      console.error(`Failed to load icon "${name}":`, error);
      return { default: (() => <div className="w-6 h-6" aria-hidden />) as any };
    })
  );
  
  return (
    <Suspense fallback={<div className="w-6 h-6" />}>
      <LucideIcon {...props} />
    </Suspense>
  );
};

interface ServicesProps {
  onStrategyClick?: () => void;
  onGovernanceClick?: () => void;
}

export const Services = ({ onStrategyClick, onGovernanceClick }: ServicesProps) => {
  const { t } = useTranslation();
  const { services, loading } = useServiceContent();

  const handleServiceClick = (service: any) => {
    if (service.clickable && service.scrollTo) {
      if (service.id === 'strategy') {
        onStrategyClick?.();
      } else if (service.id === 'governance') {
        onGovernanceClick?.();
      }
      
      setTimeout(() => {
        const section = document.getElementById(service.scrollTo);
        section?.scrollIntoView({ behavior: "smooth" });
      }, 100);
    }
  };

  return (
    <section className="py-24 bg-secondary/30">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl sm:text-5xl font-bold mb-4">{t("services.title")}</h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            {t("services.subtitle")}
          </p>
        </div>

        {loading ? (
          <div className="text-center py-12">
            <p className="text-muted-foreground">{t("common.loading", "Chargement...")}</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {services.map((service) => {
              const iconName = service.icon.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/([a-zA-Z])([0-9])/g, '$1-$2').toLowerCase() as keyof typeof dynamicIconImports;
              const isClickable = service.clickable;
              
              return (
                <Card 
                  key={service.id}
                  className={`hover:shadow-large transition-all duration-300 hover:-translate-y-1 border-border bg-card ${
                    isClickable ? 'cursor-pointer' : ''
                  }`}
                  onClick={isClickable ? () => handleServiceClick(service) : undefined}
                >
                  <CardHeader>
                    <div className="w-12 h-12 rounded-lg bg-gradient-accent flex items-center justify-center mb-4">
                      <Icon name={iconName} className="w-6 h-6 text-accent-foreground" />
                    </div>
                    <CardTitle className="text-2xl">{service.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <CardDescription className="text-base leading-relaxed">
                      {service.description}
                    </CardDescription>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </section>
  );
};
